### ISSUE TITLE
Compile BAP with LLVM 3.5

### ISSUE THREAD

**Issue by perror** [BinaryAnalysisPlatform/bap#157]
I know that you do not support yet LLVM 3.5, but I was working on a patch to use LLVM 3.5 and further (see at the end of this message).

The problem is that I miss a call to `-ltinfo` (`libterminfo`) at the linking stage:

    /usr/lib/llvm-3.5/lib/libLLVMSupport.a(Process.o): In function `llvm::sys::Process::FileDescriptorHasColors(int)':
    (.text._ZN4llvm3sys7Process23FileDescriptorHasColorsEi+0x47): undefined reference to `setupterm'
    /usr/lib/llvm-3.5/lib/libLLVMSupport.a(Process.o): In function `llvm::sys::Process::FileDescriptorHasColors(int)':
    (.text._ZN4llvm3sys7Process23FileDescriptorHasColorsEi+0x78): undefined reference to `tigetnum'
    /usr/lib/llvm-3.5/lib/libLLVMSupport.a(Process.o): In function `llvm::sys::Process::FileDescriptorHasColors(int)':
    (.text._ZN4llvm3sys7Process23FileDescriptorHasColorsEi+0x81): undefined reference to `set_curterm'
    /usr/lib/llvm-3.5/lib/libLLVMSupport.a(Process.o): In function `llvm::sys::Process::FileDescriptorHasColors(int)':
    (.text._ZN4llvm3sys7Process23FileDescriptorHasColorsEi+0x89): undefined reference to `del_curterm'
    collect2: error: ld returned 1 exit status
    File "caml_startup", line 1:
    Error: Error during linking
    Command exited with code 2.
    Compilation unsuccessful after building 538 targets (523 cached) in 00:00:04.
    Makefile:7: recipe for target 'build' failed
    make: *** [build] Error 1

And, as I am new to `ocamlbuild`, I would like to know how to add `-ltinfo` to the ocamlbuild process.

Here is my current patch for LLVM 3.5:

    diff --git a/lib/bap_disasm/llvm_disasm.cpp b/lib/bap_disasm/llvm_disasm.cpp
    index 2927df2..a7c3841 100644
    --- a/lib/bap_disasm/llvm_disasm.cpp
    +++ b/lib/bap_disasm/llvm_disasm.cpp
    @@ -1,4 +1,3 @@
    -#include <llvm/ADT/OwningPtr.h>
     #include <llvm/MC/MCAsmInfo.h>
     #include <llvm/MC/MCContext.h>
     #include <llvm/MC/MCDisassembler.h>
    @@ -177,7 +176,7 @@ public:
             }
 
 
    -        llvm::OwningPtr<llvm::MCRelocationInfo>
    +        std::unique_ptr<llvm::MCRelocationInfo>
                 rel_info(target->createMCRelocationInfo(triple, *ctx));
 
             if (!rel_info) {
    @@ -186,13 +185,13 @@ public:
                 return {nullptr, bap_disasm_unsupported_target};
             }
 
    -        llvm::OwningPtr<llvm::MCSymbolizer>
    +        std::unique_ptr<llvm::MCSymbolizer>
                 symbolizer(target->createMCSymbolizer(
                                triple,
                                nullptr, // getOpInfo
                                nullptr, // SymbolLookUp
                                nullptr, // DisInfo
    -                           &*ctx, rel_info.take()));
    +                           &*ctx, rel_info.release()));
 
             if (!symbolizer) {
                 if (debug_level > 0)
    @@ -214,7 +213,7 @@ public:
             printer->setPrintImmHex(true);
 
             shared_ptr<llvm::MCDisassembler>
    -            dis(target->createMCDisassembler(*sub_info));
    +	         dis(target->createMCDisassembler(*sub_info, *ctx));
 
             if (!dis) {
                 if (debug_level > 0)
    @@ -222,12 +221,7 @@ public:
                 return {nullptr, bap_disasm_unsupported_target};
             }
 
    -        dis->setSymbolizer(symbolizer);
    +        dis->setSymbolizer(std::move(symbolizer));
    -        dis->setupForSymbolicDisassembly(
    -            nullptr, // getOpInfo
    -            nullptr, // SymbolLookUp
    -            nullptr, // DisInfo,
    -            &*ctx, rel_info);
 
             shared_ptr<llvm_disassembler> self(new llvm_disassembler(debug_level));
             self->printer  = printer;

**Comment by ivg** [comment]
This should be as simple, as adding `-ltinfo`, to the [oasis](https://github.com/ivg/bap/blob/master/_oasis#L259) `CCLib` field. Btw, is this library from LLVM? its quite strange to see it as a dependency, anyway.

**Comment by ivg** [comment]
This is of course short and dirty method, more correct way would be to add a definition to `setup.ml.in`. But for experimenting the former is pretty fine.

**Comment by perror** [comment]
You are right, this requisite is dubious... I don't know why the build-system is needing it. Moreover, when I try to give it, it requires more... I need to investigate a bit more. 

But, I am new to oasis and the build-system of OCaml. So, I am currently trying to learn, I may have done something bad at some point. But, feel free to try my patch, I don't think it is the cause of my current problems.

**Comment by dbrumley** [comment]
As a note, this has moved up to llvm-3.7.  Note the latest ubuntu 16.04 doesn't has llvm-3.4 installed, so BAP won't build on the latest trusty anymore.

**Comment by ivg** [comment]
BAP will build on Trusty. It currently doesn't work on Xenial out of box, although it might work with llvm-3.5 toolchain that is still available on it (should double check).

**Comment by perror** [comment]
This issue should be marked as "closed", no?

**Comment by ivg** [comment]
Nope, it is still open, as our backend works only for LLVM-3.4. As time passes, the issue become more and more hot.

**Comment by ivg** [comment]
We decided to skip 3.5 and jump directly to 3.8. Currently in the process of merging.

**Comment by ivg** [comment]
The 3.8 is merged, so we support 3.4 and 3.8 the two versions that are default for the 3  lastest ubuntu LTS (12,14,16, aka Precise, Trusty and Xenial)
