### ISSUE TITLE
MAKE failed when installing bap.1.2.0 from sources.

### ISSUE THREAD

**Issue by forward-wfw** [BinaryAnalysisPlatform/bap#696]
Hi,

I'm trying out BAP with little knowledge about ocaml. I used the rpm binary distribution but BYTEWEIGHT is not integrated so I needed to install it from sources with opam.

The installation worked fine on my Ubuntu 16.04 VM, but I encountered a compilation error when trying to install on CentOS 7.

I have llvm and clang 3.8.1 installed and no other versions, with conf-llvm.3.8 installed. opam is set to version 4.02.3. When trying to install bap with `bap depext --install bap`, a compilation error raised, and the same error appeared when trying to compile from the build directory with `make`:

```
/home/fuwei.wfw/.opam/4.02.3/bin/ocamlfind ocamlc -c -g -annot -bin-annot -short-paths -I lib/bap_config -I lib/bap_types -I lib/bap_image -I lib/bap_disasm -I lib/bap_sema -I lib/bap_bundle -I lib/bap_plugins -I lib/bap -pp 'ppx-jane -dump-ast -inline-test-lib bap' -predicates ppx_driver -package ppx_jane -package fileutils -package core_kernel -package uri -package unix -package camlzip -package findlib -package compiler-libs -package zarith -package uuidm -package regular -package ppx_variants_conv -package ppx_here -package ppx_enumerate -package ocamlgraph -package graphlib -package dynlink -package compiler-libs.common -package cmdliner -package bap-future -I lib/bap -I lib/bap_config -I lib/bap_disasm -I lib/bap_image -I lib/bap_plugins -I lib/bap_sema -I lib/bap_types -o lib/bap/bap_project.cmo lib/bap/bap_project.ml`
/home/fuwei.wfw/.opam/4.02.3/bin/ocamlfind ocamlc -c -g -annot -bin-annot -short-paths -I lib/bap_config -I lib/bap_types -I lib/bap_image -I lib/bap_disasm -I lib/bap_sema -I lib/bap_bundle -I lib/bap_plugins -I lib/bap -pp 'ppx-jane -dump-ast -inline-test-lib bap' -predicates ppx_driver -package ppx_jane -package fileutils -package core_kernel -package uri -package unix -package camlzip -package findlib -package compiler-libs -package zarith -package uuidm -package regular -package ppx_variants_conv -package ppx_here -package ppx_enumerate -package ocamlgraph -package graphlib -package dynlink -package compiler-libs.common -package cmdliner -package bap-future -I lib/bap -I lib/bap_config -I lib/bap_disasm -I lib/bap_image -I lib/bap_plugins -I lib/bap_sema -I lib/bap_types -o lib/bap/bap_self.cmo lib/bap/bap_self.ml`
/home/fuwei.wfw/.opam/4.02.3/bin/ocamlfind ocamlc -c -g -annot -bin-annot -short-paths -I lib/bap_config -I lib/bap_types -I lib/bap_image -I lib/bap_disasm -I lib/bap_sema -I lib/bap_bundle -I lib/bap_plugins -I lib/bap -pp 'ppx-jane -dump-ast -inline-test-lib bap' -predicates ppx_driver -package ppx_jane -package fileutils -package core_kernel -package uri -package unix -package camlzip -package findlib -package compiler-libs -package zarith -package uuidm -package regular -package ppx_variants_conv -package ppx_here -package ppx_enumerate -package ocamlgraph -package graphlib -package dynlink -package compiler-libs.common -package cmdliner -package bap-future -I lib/bap -I lib/bap_config -I lib/bap_disasm -I lib/bap_image -I lib/bap_plugins -I lib/bap_sema -I lib/bap_types -o lib/bap/bap_self.cmo lib/bap/bap_self.ml`

File "lib/bap/bap_self.ml", line 180, characters 20-75:`

Error: This expression has type 'a -> 'b -> unit -> unit`
       but an expression was expected of type ('c -> 'd) t`

Command exited with code 2.`

make: *** [build] Error 1`
```

Having checked the code snippet, and they don't seem to mean anything to me (not dive into the ocaml language yet...)

```
180       main := Term.(const (fun x () ->`
181           Promise.fulfill promise x) $ t $ (!main));`
```

Anyone has a clue about this error?

**Comment by ivg** [comment]
Hmm... this is very strange. Can you please provide with the set of packages that you're using, so that we can try to reproduce the issue. For that just do:
```
opam switch export opam.packages
```
and upload the `opam.packages` file here.

**Comment by ivg** [comment]
Meanwhile we have a clue, that since you're building from sources your configuration doesn't conform with the constraints specified in opam. Most likely you have an incorrect version of cmdliner, bap.1.2.0 can be compiled only with cmdliner.0.9.8.

**Comment by ivg** [comment]
> I used the rpm binary distribution but BYTEWEIGHT is not integrated so I needed to install it from sources with opam

As a side note, why do you think that byteweight is not integrated? It should be there, do you have any problems with it?

**Comment by forward-wfw** [comment]
> upload the opam.packages file here.

Here is the complete list.
[opam.packages.txt](https://github.com/BinaryAnalysisPlatform/bap/files/1240920/opam.packages.txt)

> bap.1.2.0 can be compiled only with cmdliner.0.9.8.

Yes... Through tries and errors I figured out that cmdliner.0.9.8 may be necessary. However, upgrading cmdliner from 0.9.6 to 0.9.8 required to downgrade conf-llvm from 3.8 to 3.4 according to `depext`, which required to downgrade llvm/clang also.

I also tried compiling and installing llvm-3.4 and clang-3.4 alongside the 3.8 version and made 3.4 default. That yielded some bigger problem - When I tried to MAKE from the cmdliner directory, it showed: `FATAL ERROR: STACK OVERFLOW`.

**Comment by forward-wfw** [comment]
> As a side note, why do you think that byteweight is not integrated? It should be there, do you have any problems with it?

Yeah, I can see that plugin `byteweight` is integrated, but bap-byteweight-frontend is not. So I could use this plugin to extract function boundaries, but signature updating/training may not be feasible... Dunno if that is correct.

**Comment by ivg** [comment]
Yeah, `bap-byteweight-frontend` is not a part of binary distribution, it has to many dependencies. 

Unless you really have good reasons to build bap manually (e.g., you're changing the sources), it would be much easier to install bap using OPAM. Basically, what you need is just to tell

```
opam install bap bap-byteweight-frontend
```

It might be the case, that you already broke somehow your opam switch¹ by compiling something from sources and installing. Thus, my suggestion would be to create from scratch:

```
opam switch 4.03.0 #creates a new opam switch
eval `opam config env` #activates the switch
opam install bap bap-byteweight-frontend  #installs bap and byteweight-frontend
```
¹) a switch, in OPAM parlance, is an isolated OCaml virtual environment consisting of a compiler and a set of libraries. 

P.S. Do not forget that we have a [gitter][1] channel where you can easily get help and chat with BAP users and developers

[1]: https://gitter.im/BinaryAnalysisPlatform/bap

**Comment by forward-wfw** [comment]
Thanks for the infomation.

As far as I can understand, the `opam install` procedure is done by automatically fetching the source codes and `make & install` the binary with default dependencies and corresponding versions.

As I moved forward to solving more problems on CentOS, even more appeared... I finally succeeded in compiling & installing llvm-clang 3.4.2, downgrading conf-llvm package to 3.4, upgrading cmdliner to 0.9.8, and installing bap through opam with `opam depext --install bap`. Everything is done, but when I tried using this installed bap, the following errors appear:

`loader.error> Failed to load plugin "x86": Failed to load bap_llvm: error loading shared library: /tmp/bap_llvm68b222.cmxs: undefined symbol: _ZTIN4llvm12MemoryObjectE`

`loader.error> Failed to load plugin "llvm": Failed to load bap_llvm: error loading shared library: /tmp/bap_llvmc17029.cmxs: undefined symbol: _ZTIN4llvm12MemoryObjectE`

Still no clue about why the installed bap-llvm plugin is missing this symbol. So I figured out maybe it's just too unwise to use bap on CentOS without the prebuilt rpms...

However, using the prebuilt rpms, executing bap with byteweight plugin yielded some other problem (something like `wrong memory scale 0`)... Maybe I should ask these thing on the gitter channel~

**Comment by ivg** [comment]
> As far as I can understand, the opam install procedure is done by automatically fetching the source codes and make & install the binary with default dependencies and corresponding versions.

Yes, but it will take care of all the dependencies, so that you can use 3.8 and the right version of cmdliner, and not even be aware of them. 

> the following errors appear:
```
loader.error> Failed to load plugin "x86": Failed to load bap_llvm: error loading shared library: /tmp/bap_llvm68b222.cmxs: undefined symbol: _ZTIN4llvm12MemoryObjectE
```

It is hard to guess, I have two ideas:
1.You somehow mixed your manual attempts of installation and/or binary installation and/or opam installation. 
2. Your llvm installation is broken. 

I would bet for the latter, as plugin is self contained and statically links the llvm library. So the fact that something is undefined, means that your downgrade didn't work right.

> However, using the prebuilt rpms, executing bap with byteweight plugin yielded some other problem (something like Failed to create a project: ("invalid memory scale" 0))... 

That's something new. Did it break on any file with such error, or it was a specific file? Also was it a prebuilt version of BAP or not?


>  So I figured out maybe it's just too unwise to use bap on CentOS without the prebuilt rpms...

I would expect BAP to work fine on CentOS, but looks like that you chose a path of the greatest resistance :) So my suggestion would be to start from the clean state. If it was a VM creating a new one would be a good idea.  Then just do

```
opam depext --install conf-llvm.3.8 bap bap-byteweight-frontend
```
